# -*- coding: utf-8 -*-
"""final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OnrsE9Ma2HuaRzGdEVBcP6YFCnqcDcMa

AVD Final

Gustavo Lima Carvalho (202010404)

1. Instalar o Pytesseract e o tesseract-OCR no Colab;
"""

# Instalando o Pytesseract e o tesseract-OCR
! sudo apt install tesseract-ocr 
! pip install pytesseract

# Instalando as bibliotecas necessárias
import pytesseract
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

import numpy as np
import pandas as pd
import cv2
from google.colab.patches import cv2_imshow
from skimage import io
from PIL import Image 
import matplotlib.pylab as plt
import scipy

"""2. Carregar imagem que contenha texto para o Colab;

3. Chamar a função que recebe uma imagem de entrada e extrai o seu texto. Imprimir o texto reconhecido na tela;
"""

# Importando imagem e convertendo de RGB para BGR
image = cv2.imread('image.png')
image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

# Utilizando o pytesseract para obter o texto da imagem e imprimi-los
cv2_imshow(image)

imageText = pytesseract.image_to_string(image)
print(imageText)

"""4. Obter as coordenadas das caixas envolventes ao redor de cada palavra, e imprima um retângulo VERDE para cada caixa envolvente encontrada usando OpenCV. Utilize a função cv::Rectangle para isso;"""

# Utilizando o pytesseract para obter as coordenadas das palavras identificadas
print(pytesseract.image_to_data(image))

# A partir destas coordenadas, é utilizada a função cv.rectangle para imprimir um retângulo verde nas palavras encontradas na imagem
cv2.rectangle(image, pt1=(48,39), pt2=( (48+220), (39+41) ), color=(0,255,0), thickness=1)
cv2.rectangle(image, pt1=(288,39), pt2=( (288+149), (39+41) ), color=(0,255,0), thickness=1)
cv2.rectangle(image, pt1=(33,176), pt2=( (33+124), (179+30) ), color=(0,255,0), thickness=1)
cv2.rectangle(image, pt1=(172,176), pt2=( (172+93), (176+30) ), color=(0,255,0), thickness=1)
cv2.rectangle(image, pt1=(284,176), pt2=( (284+167), (176+30) ), color=(0,255,0), thickness=1)

# Impressão do resultado final
cv2_imshow(image)